### ISSUE TITLE
Add border to color-picker buttons

### ISSUE THREAD

**Issue by melchoyce** [ryelle/queeromattic-flags#1]
If you can Sass it, thinking the picked color, darkened by 10–20%. This'll help when selecting lighter colors:

![image](https://user-images.githubusercontent.com/2846578/32905655-8c4b9ade-cac8-11e7-8ee7-1f0e39b98a49.png)

**Comment by ryelle** [comment]
Can't sass it like that, but what about this? it's just a 20% opacity black, but easy to CSS. otherwise i'll have to calc the color in JS, which.. is doable, but this is easy 🙂 

<img width="354" alt="screen shot 2017-11-16 at 8 49 13 pm" src="https://user-images.githubusercontent.com/541093/32925385-b2273e1a-cb0f-11e7-962f-613ce4b7c3b8.png">

**Comment by melchoyce** [comment]
I think that works, though I also think there should be a border on the right of the color picker button.
